project:
  type: website
  output-dir: docs
  resources:
    - files/

# Meta
description-meta: "Kevin Carrasco - Sociólogo y Magíster en Ciencias sociales"
author-meta: "Kevin Carrasco"

website:
  title: "Kevin Carrasco"
  image: "/files/profile/kevin-carrasco.jpg"
  description: "Kevin Carrasco es un sociólogo y magíster en Ciencias sociales. "
 
  navbar:
    background: dark

    left:
#      - text: Home
#        href: index.qmd   
      - text: "Investigación"
        menu:
          - text: "Publicaciones"
            href: references/publications/index.qmd
          - text: "Presentaciones"
            href: references/presentations/index.qmd                           
      - text: Docencia
        href: teaching.qmd


    right: 
      - text: "**CV**"
        href: files/cv-esp.pdf
        target: _blank 
      - icon: github
        href: https://github.com/kevin-carrasco
        target: _blank
#      - text: "{{< fa brands bluesky >}}"
#        href: https://bsky.app/profile/hegang.bsky.social
#        target: _blank
      - icon: twitter-x 
        href: https://twitter.com/kevincarrascoq1
        target: _blank        

  
  page-navigation: true
  
  page-footer: 
    center: "[Kevin Carrasco](http://kevin-carrasco.github.io) &copy; <script>document.write(new Date().getFullYear())</script>"
    # left: "[Kevin Carrasco](http://kevin-carrasco.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    right:  
       - icon: github
         href: https://github.com/kevin-carrasco/kevin-carrasco.github.io
    #     target: _blank
    #   - text: "{{< fa brands bluesky >}}" 
    #     href: https://bsky.app/profile/hegang.bsky.social
    #     target: _blank
    #   - icon: rss
    #     href: posts.xml
    #     target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: false

  draft-mode: unlinked
  
  repo-url: https://github.com/kevin-carrasco/kevin-carrasco.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://kevin-carrasco.github.io"
  

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    extensions:
      - banner-override
    include-in-header:
      - "files/includes/_academic.qmd"
      - "translate.html"
