---
title: "Investigación"
description-meta: "Papers y otros"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: /custom.css
---

## papers

- Pérez-Ahumada, P., Olivares-Collío, D., & Carrasco, K. (2026). The conditioning power of class: Collective action and attitudes toward inequality in neoliberal Chile (2016–2023). Critical Sociology, 08969205261417585. [https://doi.org/10.1177/08969205261417585](https://doi.org/10.1177/08969205261417585)

- Castillo, J. C., Laffert, A., Carrasco, K., & Iturra-Sanhueza, J. (2025). Perceptions of inequality and meritocracy: Their interplay in shaping preferences for market justice in Chile (2016–2023). Frontiers in Sociology, 10, 1634219. [https://doi.org/10.3389/fsoc.2025.1634219](https://doi.org/10.3389/fsoc.2025.1634219)

- Castillo, J. C., Iturra, J., & Carrasco, K. (2025). Changes in the Justification of Educational Inequalities: The Role of Perceptions of Inequality and Meritocracy During the COVID Pandemic. Social Justice Research, 38(3), 240-263. [https://doi.org/10.1007/s11211-025-00458-0](https://doi.org/10.1007/s11211-025-00458-0)

- Castillo, J. C., Salgado, M., Carrasco, K., & Laffert, A. (2024). The Socialization of Meritocracy and Market Justice Preferences at School. Societies, 14(11), 214. [https://doi.org/10.3390/soc14110214](https://doi.org/10.3390/soc14110214)

- Pérez-Ahumada, P., & Carrasco, K. (2025). Política de clases y confianza en los sindicatos en América Latina. Latin American Research Review, 60(2), 410-433. [https://doi.org/10.1017/lar.2024.64](https://doi.org/10.1017/lar.2024.64)

- Castillo, J. C., & Carrasco, K. (2024). Brechas de género en la percepción y justificación de la desigualdad salarial en Chile 1999-2019. Estudios Públicos, 1-41. [https://doi.org/10.38178/07183089/1152230428](https://doi.org/10.38178/07183089/1152230428)


## Capítulos de libros

- Miranda, D., Castillo, J. C., Carrasco, K., & Herrera-Leighton, A. (2025). The Political Participation of Latin American School-age Students. En H. Çakal, D. Sirlopú, & V. Smith-Castro, The Political Psychology of Social Unrest in Latin America (1.ª ed., pp. 104-122). Routledge. [https://doi.org/10.4324/9781003282174-6](https://doi.org/10.4324/9781003282174-6)

- Carrasco, K., García-Castro, J. D., & Castillo, J. C. (2024). La socialización de las actitudes hacia la desigualdad y meritocracia en la etapa escolar en Chile. En G. Assusa & G. Benza (Eds.), América Latina desigual. Preguntas, enfoques y tendencias actuales (Clacso y Siglo ventiuno editores, pp. 205-234). [Researchgate](https://www.researchgate.net/publication/385132484_La_socializacion_de_las_actitudes_hacia_la_desigualdad_y_meritocracia_en_la_etapa_escolar_en_Chile#fullTextFileContent)

## Presentaciones
- Juan-Carlos Castillo, Kevin Carrasco (2025). Cambio en las creencias sobre meritocracia y justicia de mercado en el contexto escolar. VIII seminario internacional DEMOSAL. Río de Janeiro, Brazil.

- Juan-Carlos Castillo, Kevin Carrasco (2024). Meritocracia y redistribución: Evolución de las percepciones y preferencias en el contexto escolar. XI Conferencia Internacional COES. Viña del Mar, Chile.

- Juan-Carlos Castillo, Kevin Carrasco (2024). Meritocracia y justificación de la desigualdad en la etapa escolar: Un experimento de encuesta. Congreso chileno de Sociología - PreAlas. Santiago, Chile.

- Pre-registros y ciencia abierta- Seminario COES 2023. Stgo, Chile-[https://lisa-coes.github.io/presentaciones/workshopelsocseptiembre2022/workshopelsoc-sept2022.html](https://lisa-coes.github.io/presentaciones/workshopelsocseptiembre2022/workshopelsoc-sept2022.html)

- Socialización de la meritocracia en la escuela y justificación de la desigualdad económica. Conferencia DEMOSAL 2023. Buenos aires, Argentina [https://educacion-meritocracia.github.io/meritocracia-escuela-agencia/presentations//demosal2023/](https://educacion-meritocracia.github.io/meritocracia-escuela-agencia/presentations//demosal2023/)

- Brechas de género en la percepción y justificación de desigualdad salarial. Conferencia DEMOSAL 2023. Buenos aires, Argentina [https://justicia-distributiva.github.io/brechas-genero/presentations/DEMOSAL2023/DEMOSAL2023.html](https://justicia-distributiva.github.io/brechas-genero/presentations/DEMOSAL2023/DEMOSAL2023.html)

- Control multidimensional en la economia gig. El caso de las plataformas de reparto en Chile y Argentina. Conferencia DEMOSAL 2023. Buenos aires, Argentina

- Aceptar la diversidad en el Vecindario: Procesos de Socialización política de actitudes hacia la diversidad en jóvenes estudiantes chilenos. Conferencia COES 2022. Stgo, Chile [https://kevin-carrasco.github.io/presentacion-tesis/coesconf-2022/presentacion.html](https://kevin-carrasco.github.io/presentacion-tesis/coesconf-2022/presentacion.html)    

- Meritocracia, Preferencias redistributivas y Socialización política escolar. Conferencia COES 2022. Stgo, Chile [https://educacion-meritocracia.github.io/meritocracia-escuela-agencia/presentacion-coes-conf-2022/presentacion-edumer.html](https://educacion-meritocracia.github.io/meritocracia-escuela-agencia/presentacion-coes-conf-2022/presentacion-edumer.html)

- Aceptar la diversidad en el Vecindario: Procesos de Socialización política de actitudes hacia la diversidad en jóvenes estudiantes chilenos. Congreso ALAS 2022. México (Online) [https://kevin-carrasco.github.io/presentaciontesis/presentacion-alas/presentacion.html](https://kevin-carrasco.github.io/presentaciontesis/presentacion-alas/presentacion.html)

- El rol de la Familia y la escuela en la Socialización política de actitudes hacia la igualdad de género. Conferencia DEMOSAL 2021. México (online)