---
title: "Docencia"
subtitle: "Enseño principalmente sobre estadística y R aplicado a las ciencias sociales"
description-meta: "Todos los cursos cuentan con material de enseñanza disponible en GitHub."
title-block-banner: false
---

Profesor de la cátedra “Métodos Estadísticos para las Ciencias Sociales III” de la Universidad Andrés Bello y del curso electivo "R para el análisis de datos sociales" de la Universidad Alberto Hurtado.

Enseño principalmente sobre estadística y R aplicado a las ciencias sociales. Todos los cursos cuentan con material de enseñanza disponible en GitHub.

## Actualmente

- [R para el análisis de datos sociales](https://r-data-analisis.netlify.app/) - Sociología Universidad Alberto Hurtado

- [Métodos Estadísticos para las Ciencias Sociales III](https://metod3-unab.netlify.app/) - Sociología Universidad Andrés Bello

## Anteriores cursos

- [Estadística IV](https://estadisticaiv.netlify.app/) - Sociología Universidad Alberto Hurtado

- [Metodología I](https://metod1.netlify.app/) - Magíster en Ciencias Sociales Universidad de Chile

- [Metodología cuantitativa avanzada](https://metod2-mcs.netlify.app/) - Magíster en Ciencias Sociales Universidad de Chile

## Como apoyo docente

- [Estadística correlacional](https://correlacional.netlify.app/)  - Sociología Universidad de Chile

- [Análisis de datos multinivel](https://multinivel-facso.netlify.app/) - Sociología Universidad de Chile

- Estrategias de investigación cuantitativa - Sociología Universidad de Chile

- Diseños de investigación - Sociología Universidad de Chile

- Estadística descriptiva - Sociología Universidad de Chile

- Estadística multivariada - Sociología Universidad de Chile


